export const SET_RECIPE_FILTER = 'SET_RECIPE_FILTER';
export const CLEAR_RECIPE_FILTER = 'CLEAR_RECIPE_FILTER';

export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const RECEIVE_RECIPES_SUCCESS = 'RECEIVE_RECIPES_SUCCESS';
export const RECEIVE_RECIPES_FAILURE = 'RECEIVE_RECIPES_FAILURE';
